[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
  package = "@netlify/plugin-gatsby"
  
[[plugins]]
  package = "/plugins/netlify-plugin-process-notifications"

[build.processing.html]
  pretty_urls = false